### ISSUE TITLE
Unable to rebuild system with programs.spicetify enabled.

### ISSUE THREAD

**Issue by BelgianDev** [Gerg-L/spicetify-nix#242] opened 2024-11-22 22:09 UTC
Hey, I'm trying to rebuild my system with the example config you gave in your README, but my system fails to build, I don't know if it's related to something on my side or if something broke.

Here is the log:
```
warning: The interpretation of store paths arguments ending in `.drv` recently changed. If this command is now failing try again with '/nix/store/kbp3il42pxxqfp5lkpa4mcna5kg7pmmx-spicetify-catppuccin.drv^*'
@nix { "action": "setPhase", "phase": "unpackPhase" }
Running phase: unpackPhase
Parallel unsquashfs: Using 12 processors
107 inodes (2529 blocks) to write



created 106 files
created 10 directories
created 1 symlink
created 0 devices
created 0 fifos
created 0 sockets
created 0 hardlinks
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: patchPhase
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
Running phase: configurePhase
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
Running phase: buildPhase
no Makefile or custom buildPhase, doing nothing
@nix { "action": "setPhase", "phase": "glibPreInstallPhase" }
Running phase: glibPreInstallPhase
@nix { "action": "setPhase", "phase": "glibPreInstallPhase" }
Running phase: glibPreInstallPhase
@nix { "action": "setPhase", "phase": "installPhase" }
Running phase: installPhase
spicetify v2.36.14
Backing up app files:
OK
Extracting:
OK
Preprocessing:
warning Cannot fetch version tag for CSS mappings
err: Get "https://api.github.com/repos/spicetify/cli/releases/latest": dial tcp: lookup api.github.com on [::1]:53: read udp [::1]:48755->[::1]:53: read: connection refused
info Fetching remote CSS map for newer compatible tag version: 2.36.14
info Cannot fetch remote CSS map. Using local CSS map instead...
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/spicetify/cli/src/preprocess.exposeAPIs_main({0xc0028f2000, 0x2d2941})
        github.com/spicetify/cli/src/preprocess/preprocess.go:560 +0x573
github.com/spicetify/cli/src/preprocess.Start.func1.1({0xc00234a000, 0x2d1f7f})
        github.com/spicetify/cli/src/preprocess/preprocess.go:103 +0x192
github.com/spicetify/cli/src/utils.ModifyFile({0xc00002e0c0, 0x2f}, 0xc00015b9e8)
        github.com/spicetify/cli/src/utils/utils.go:221 +0xbc
github.com/spicetify/cli/src/preprocess.Start.func1({0xc00002e0c0, 0x2f}, {0x7c4928?, 0xc000190270?}, {0x0?, 0x0?})
        github.com/spicetify/cli/src/preprocess/preprocess.go:91 +0x145
path/filepath.walk({0xc00002e0c0, 0x2f}, {0x7c4928, 0xc000190270}, 0xc00015bca8)
        path/filepath/path.go:478 +0x105
path/filepath.walk({0xc0001b8090, 0x27}, {0x7c4928, 0xc00195e340}, 0xc0001a9ca8)
```

This also happends by simply enabling Spicetify without any theme or extensions.

Spotify is installed as Home Manager package

**Comment by Gerg-L** [comment] 2024-11-23 16:14
I believe this is a duplicate of #238

**Closed as completed by Gerg-L** 2024-11-23 16:14 UTC
